
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2jwt
    username: root
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
    mode: never

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create

  security:
    oauth2:
      client:

        registration:
          naver:
            client-name: naver
            client-id: knAYu73hTGCssF6ukCWE
            client-secret: TWRQJypi4l
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb


server:
  port: 8080